analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.349099
  lightness: 0.521395
  rhythmicContrast: 0.519144
  saturation: 0.472972
cta: {}
layout_spectrum: 0.708333
name: 'kevin morris photography '
opengraph: {}
purpose: []
typography_spectrum: 0.38561
