name: 'kevin morris photography '
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39b6d31c-8673-4a49-a663-4db5f42fe219.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a28f0e4-9aed-4216-a4a7-6633b6d6bd65.jpg
layout_spectrum: 0.5101904468610883
typography_spectrum: 0.42661410151049495
cta: {}
analytics:
  google: UA-79494229-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#010101'
    - '#293332'
    - '#C6B4AA'
    - '#6C6C6E'
    - '#979A9F'
  brandStrength: 0.75
  lightness: 0.521395
  saturation: 0.472972
  rhythmicContrast: 0.75
purpose: []
title: freelance photographer
author:
  name: kevin morris
  url: ''
  email: 'kevinmorrisphoto@gmail.com '
content_rating:
  adult: false
