name: 'kevin morris photography '
layout_spectrum: 0.5101904468610883
typography_spectrum: 0.42661410151049495
cta: {}
analytics:
  google: UA-79494229-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#010101'
    - '#293332'
    - '#C6B4AA'
    - '#6C6C6E'
    - '#979A9F'
  brandStrength: 0.75
  lightness: 0.521395
  saturation: 0.472972
  rhythmicContrast: 0.75
purpose: []
title: freelance photographer
author:
  name: kevin morris
  url: ''
  email: 'kevinmorrisphoto@gmail.com '
content_rating:
  adult: false
