analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.662162
  lightness: 0.521395
  rhythmicContrast: 0.278153
  saturation: 0.524774
cta: {}
layout_spectrum: 0.409909
name: 'kevin morris photography '
opengraph: {}
purpose: []
typography_spectrum: 0.613738
