typography_spectrum: 0.42661410151049495
color:
  brandColors:
    - '#010101'
    - '#293332'
    - '#C6B4AA'
    - '#6C6C6E'
    - '#979A9F'
  brandStrength: 0.75
  lightness: 0.521395
  saturation: 0.472972
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2679698776919395
analytics:
  google: UA-79494229-1
  facebook: null
  twitter: null
author:
  name: kevin morris
  email: 'kevinmorrisphoto@gmail.com '
  url: ''
name: 'kevin morris photography '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: feelance photographer
purpose: []
