name: 'kevin morris photography '
favicon: null
layout_spectrum: 0.6281507620587945
typography_spectrum: 0.4616849757730961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08151039970107377
  lightness: 0.5213966716546565
  saturation: 0.7350126570090652
  rhythmicContrast: 0.20444929087534547
purpose: []
