name: 'kevin morris photography '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38561
title: kevin morris photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#293332'
    - '#C6B4AA'
    - '#6C6C6E'
    - '#979A9F'
  brandStrength: 0.75
  lightness: 0.521395
  saturation: 0.472972
  rhythmicContrast: 0.75
purpose: []
