analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.318693
  lightness: 0.521395
  rhythmicContrast: 1
  saturation: 0.472972
cta: {}
layout_spectrum: 0.588964
name: 'kevin morris photography '
opengraph: {}
purpose: []
typography_spectrum: 0.59572
